version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-helloworld-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r0yhj8v58psj"
s3_prefix = "sam-helloworld-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
